# Jupyter Book Configuration
title: "Machine Learning Predicci√≥n - Libro"
author: "Manuel y Diego"
logo: ""
execute:
  execute_notebooks: "off"

html:
  favicon: ""
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
